### ISSUE TITLE
ASFBuffBot和最新ASF版本不兼容

### ISSUE THREAD

**Issue by Megalounge** [chr233/ASFBuffBot#3]
**ASFBuffBot和最新ASF版本不兼容**

**Error Log / 错误日志**
Please paste the error log of ASFBuffBot, for example
请在此粘贴 ASFBuffBot 的错误日志, 示例如下

```txt
ASFBuffBot 遇到错误, 日志如下
==========================================
 - ASF 版本: 5.4.8.3
 - 插件版本: 1.0.8.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
2023-08-04 13:00:26|ArchiSteamFarm-11484|INFO|ASF|InitPlugins() 正在初始化 Plugins……
2023-08-04 13:00:26|ArchiSteamFarm-11484|ERROR|ASF|InitPlugins() 因发生此错误而失败：ASFBuffBot, Version=1.0.8.0, Culture=neutral, PublicKeyToken=null
2023-08-04 13:00:26|ArchiSteamFarm-11484|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException
2023-08-04 13:00:36|ArchiSteamFarm-11484|INFO|ASF|UpdateAndRestart() ASF 将每隔 1 天自动检查新版本。
2023-08-04 13:00:36|ArchiSteamFarm-11484|INFO|ASF|Update() 正在检查新版本……
2023-08-04 13:00:37|ArchiSteamFarm-11484|INFO|ASF|Update() 当前版本：5.4.8.3 | 最新版本：5.4.8.3
```

**Comment by chr233** [comment]
稍后更新

**Comment by chr233** [comment]
已更新 1.1.0.0 ，支持 5.7.8.3
