### ISSUE TITLE
获取buff api请求失败

### ISSUE THREAD

**Issue by Megalounge** [chr233/ASFBuffBot#4]
**获取buff api请求失败**
获取5次均失败

**Error Log / 错误日志**
```txt
ASFBuffBot 遇到错误, 日志如下
UrlGetToJsonObject() 请求失败：https://buff.163.com/account/api/user/info
UrlGetToJsonObject() System.TypeLoadException
   at System.ModuleHandle.ResolveType(QCallModule, Int32, IntPtr*, Int32, IntPtr*, Int32, ObjectHandleOnStack)
   at System.ModuleHandle.ResolveTypeHandle(Int32, RuntimeTypeHandle[], RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, Type[], Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule, Int32, RuntimeType, Int32, Boolean)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeMethodInfo, RuntimeType, Boolean)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.IsValidCallback(MethodInfo method, ParameterInfo[] parameters, Type attributeType, MethodInfo currentCallback, Type& prevAttributeType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType(Type type, List`1& onSerializing, List`1& onSerialized, List`1& onDeserializing, List`1& onDeserialized, List`1& onError)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(JsonContract contract, Type t)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at ArchiSteamFarm.Web.WebBrowser.UrlGetToJsonObject[T](Uri request, IReadOnlyCollection`1 headers, Uri referer, ERequestOptions requestOptions, Byte maxTries, Int32 rateLimitingDelay)
   at ArchiSteamFarm.Web.WebBrowser.UrlGetToJsonObject[T](Uri request, IReadOnlyCollection`1 headers, Uri referer, ERequestOptions requestOptions, Byte maxTries, Int32 rateLimitingDelay)
```

在经过重启. 更换代理, 手动输入cookie等操作均失败后 决定submit issue来排bug

**Comment by chr233** [comment]
加我qq吧 1142033406，需要远程看一下

**Comment by imhuimie** [comment]
一样的问题

**Comment by chr233** [comment]
反序列化仍旧有问题，请尝试使用自编译版本的ASF

需要使用 generic 后缀的ASF，或者自行编译的ASF

基于 5.4.8.3 版本编译的ASF已上传到 release

**Comment by chr233** [comment]
https://github.com/chr233/ASFBuffBot/releases/download/1.1.0.2/ASF_5.4.8.3.7z
