### ISSUE TITLE
最新版ASF启用插件会报错导致ASF意外退出

### ISSUE THREAD

**Issue by gyq180** [chr233/ASFBuffBot#7]
**Describe the bug / Bug 描述**
最新版ASF启用插件会报错导致ASF意外退出

**Error Log / 错误日志**
Please paste the error log of ASFBuffBot, for example
请在此粘贴 ASFBuffBot 的错误日志, 示例如下

```txt
ASFBuffBot 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 5.5.0.11
 - 插件版本: 1.1.1.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
 - 错误类型: System.Exception
 - 错误消息: Exception of type 'System.Exception' was thrown.
2023-12-17 15:09:05|ArchiSteamFarm-18|INFO|5|IsAnythingToFarm() 正在检查 Steam 徽章页面的第一页……
2023-12-17 15:09:11|ArchiSteamFarm-18|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<ArchiSteamFarm.Web.Responses.HtmlDocumentResponse> ArchiSteamFarm.Web.WebBrowser.UrlGetToHtmlDocument(System.Uri, System.Collections.Generic.IReadOnlyCollection`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Uri, ERequestOptions, Byte, Int32)'.
   at ASFBuffBot.Update.WebRequest.OnStatisticTimer(Object _)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFBuffBot.Update.WebRequest.OnStatisticTimer(Object _)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__30_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean )
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2023-12-17 15:09:11|ArchiSteamFarm-18|ERROR|ASF|Exit() 正在以非 0 错误代码退出！
2023-12-17 15:09:11|ArchiSteamFarm-18|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...

**Comment by chr233** [comment]
暂未适配5.5.0.10，等待更新

**Comment by chr233** [comment]
已更新
