### ISSUE TITLE
交易报价被确定为rejected

### ISSUE THREAD

**Issue by Wheatmonkey** [chr233/ASFBuffBot#9]
ASFBuffBot 遇到错误, 日志如下
2024-05-29 19:43:29|ArchiSteamFarm-17928|ERROR|ASF|注册Buff Service失败() System.InvalidCastException: Specified cast is not valid.
   at ASFBuffBot.Core.ReflectionHelper.AddBuffService()
   at ASFBuffBot.ASFBuffBot.<>c.<<OnASFInit>b__15_0>d.MoveNext()
2024-05-29 19:43:32|ArchiSteamFarm-17928|INFO|robot_1|OnConnected() 已连接到 Steam！
2024-05-29 19:43:32|ArchiSteamFarm-17928|INFO|robot_1|OnConnected() 登录中……
2024-05-29 19:43:33|ArchiSteamFarm-17928|INFO|robot_1|OnLoggedOn() 成功以 76561199678945262 的身份登录。
2024-05-29 19:43:33|ArchiSteamFarm-17928|INFO|robot_1|Init() 成功！
2024-05-29 19:43:36|ArchiSteamFarm-17928|INFO|robot_1|IsAnythingToFarm() 正在检查 Steam 徽章页面的第一页……
2024-05-29 19:43:44|ArchiSteamFarm-17928|DEBUG|robot_1|ShouldAcceptTrade() 交易报价 7056609427 被确定为 Rejected，原因是：SteamTradeMatcher = False。
2024-05-29 19:43:44|ArchiSteamFarm-17928|DEBUG|ASF|AddTradeCache() 收到新交易, ID:7056609427
2024-05-29 19:43:44|ArchiSteamFarm-17928|INFO|robot_1|ParseTrade() 忽略交易：7056609427
2024-05-29 19:43:58|ArchiSteamFarm-17928|INFO|ASF|OnBuffTimer() 开始为 robot_1 检查发货信息
2024-05-29 19:43:58|ArchiSteamFarm-17928|INFO|ASF|CheckCookiesValid() Login Required

```

**Comment by chr233** [comment]
下个月修
